;;; icon-tools-data-nerd.el --- Icon-tools nerd icon data  -*- lexical-binding: t; -*-

;; Author: Shihao Liu
;; Keywords: treemacs nerd icon
;; Version: 1.0.0
;; Package-Requires: ((emacs "24.3") (treemacs "2.9.5"))

;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 2, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth
;; Floor, Boston, MA 02110-1301, USA.
;;

;;; Commentary:
;;
;; Nerd icons data.
;; -----------------------------------------------------------------

;;; Code:

(defvar icon-tools-data-nerd-alist
  '(
    ("R"                        . " ")
    ("apache"                   . "󱀏 ")
    ("apple"                    . " ")
    ("archive"                  . "󰀼 ")
    ("asciidoc"                 . " ")
    ("assembly-generic"         . " ")
    ("atom"                     . "󰝨 ")
    ("audacity"                 . " ")
    ("aws"                      . "󰸏 ")
    ("babel"                    . " ")
    ("bibtex"                   . " ")
    ("binary"                   . " ")
    ("bolt"                     . " ")
    ("book"                     . " ")
    ("bookmark"                 . " ")
    ("bower"                    . " ")
    ("bug"                      . " ")
    ("c-line"                   . " ")
    ("cabal"                    . " ")
    ("calendar-check"           . "󰃯 ")
    ("camera-retro"             . "󰄀 ")
    ("chart-bar"                . "󰄨 ")
    ("checklist"                . " ")
    ("clojure-alt"              . " ")
    ("clojurejs"                . " ")
    ("closed_caption"           . "󰶽 ")
    ("cloud-download"           . " ")
    ("cloudy"                   . " ")
    ("cloudy-gusts"             . " ")
    ("cloudy-windy"             . " ")
    ("cmake"                    . "󰣖 ")
    ("code"                     . " ")
    ("coffeescript"             . " ")
    ("cogs"                     . "󰣖 ")
    ("commenting-dots"          . " ")
    ("commenting-o"             . " ")
    ("common-lisp"              . " ")
    ("config-go"                . " ")
    ("config-ruby"              . " ")
    ("cplusplus-line"           . "󰙲 ")
    ("crystal"                  . " ")
    ("csharp-line"              . " ")
    ("css3"                     . " ")
    ("d3"                       . " ")
    ("dart"                     . " ")
    ("dashboard"                . " ")
    ("database"                 . " ")
    ("day-cloudy"               . " ")
    ("day-cloudy-high"          . " ")
    ("day-haze"                 . " ")
    ("day-sunny"                . " ")
    ("device-desktop"           . "󰇄 ")
    ("docker"                   . " ")
    ("dropbox"                  . " ")
    ("dust"                     . " ")
    ("edit"                     . " ")
    ("elixir"                   . " ")
    ("elm"                      . " ")
    ("emacs"                    . " ")
    ("erlang"                   . " ")
    ("eslint"                   . " ")
    ("eye"                      . " ")
    ("file"                     . " ")
    ("file-arrow-down"          . " ")
    ("file-binary"              . " ")
    ("file-code"                . " ")
    ("file-directory"           . "󰉋 ")
    ("file-media"               . " ")
    ("file-pdf"                 . " ")
    ("file-text"                . " ")
    ("file-zip"                 . " ")
    ("files"                    . " ")
    ("film"                     . "󰿏 ")
    ("firefox"                  . "󰈹 ")
    ("fog"                      . "󰖑 ")
    ("folders"                  . "󰉓 ")
    ("font"                     . " ")
    ("fortran"                  . "󱈚 ")
    ("fsharp"                   . " ")
    ("gear"                     . "󰒓 ")
    ("gears"                    . "󰣖 ")
    ("gentoo"                   . "󰣨 ")
    ("git"                      . " ")
    ("git-branch"               . " ")
    ("git-commit"               . " ")
    ("git-compare"              . " ")
    ("git-merge"                . " ")
    ("gnu"                      . " ")
    ("go"                       . " ")
    ("google-drive"             . "󰊶 ")
    ("gradle"                   . " ")
    ("graph"                    . " ")
    ("graphql"                  . " ")
    ("grunt"                    . " ")
    ("gulp"                     . " ")
    ("hail"                     . " ")
    ("haml"                     . " ")
    ("haskell"                  . " ")
    ("homebrew"                 . " ")
    ("horizon"                  . " ")
    ("hot"                      . " ")
    ("html5"                    . " ")
    ("hurricane"                . "󰢘 ")
    ("hy"                       . " ")
    ("idris"                    . " ")
    ("image"                    . " ")
    ("images-alt"               . " ")
    ("info"                     . "󰋽 ")
    ("jade"                     . " ")
    ("java"                     . " ")
    ("javascript"               . "󰌞 ")
    ("typescript"               . "󰛦 ")
    ("javascript-badge"         . "󰌞 ")
    ("typescript-badge"         . "󰛦 ")
    ("jenkins"                  . " ")
    ("jinja"                    . " ")
    ("jsx-alt"                  . " ")
    ("julia"                    . " ")
    ("jupyter"                  . " ")
    ("key"                      . " ")
    ("kotlin"                   . " ")
    ("less"                     . " ")
    ("lisp"                     . " ")
    ("llvm"                     . " ")
    ("lock"                     . " ")
    ("lua"                      . " ")
    ("mail"                     . " ")
    ("mail-read"                . " ")
    ("makefile"                 . " ")
    ("mark-github"              . " ")
    ("markdown"                 . "󰍔 ")
    ("matlab"                   . "󰍘 ")
    ("message"                  . "󰍥 ")
    ("microsoft-excel"          . "󱎏 ")
    ("microsoft-powerpoint"     . "󱎐 ")
    ("microsoft-word"           . "󱎒 ")
    ("moustache"                . " ")
    ("music"                    . "󰝚 ")
    ("na"                       . " ")
    ("nginx"                    . " ")
    ("night-alt-cloudy"         . " ")
    ("night-alt-partly-cloudy"  . " ")
    ("night-clear"              . " ")
    ("nimrod"                   . " ")
    ("ninja"                    . "󰝴 ")
    ("nix"                      . "󱄅 ")
    ("nodejs"                   . "󰎙 ")
    ("npm"                      . " ")
    ("nvidia"                   . " ")
    ("ocaml"                    . " ")
    ("odin"                     . " ")
    ("org"                      . " ")
    ("org-mode"                 . " ")
    ("package"                  . " ")
    ("pencil"                   . " ")
    ("perl"                     . " ")
    ("perldocs"                 . " ")
    ("php"                      . " ")
    ("pony"                     . " ")
    ("postcss"                  . " ")
    ("powershell"               . "󰨊 ")
    ("prolog"                   . " ")
    ("pug-old"                  . " ")
    ("puppet"                   . " ")
    ("purescript"               . " ")
    ("python"                   . " ")
    ("racket"                   . " ")
    ("rain-mix"                 . " ")
    ("react"                    . "󰜈 ")
    ("reason"                   . " ")
    ("restructuredtext"         . "󱩼 ")
    ("rss"                      . " ")
    ("ruby"                     . " ")
    ("ruby-alt"                 . " ")
    ("rust"                     . " ")
    ("sass"                     . " ")
    ("sbt"                      . " ")
    ("scala"                    . " ")
    ("scheme"                   . " ")
    ("script"                   . "󰯂 ")
    ("settings"                 . " ")
    ("showers"                  . " ")
    ("sleet"                    . " ")
    ("smoke"                    . " ")
    ("snow"                     . " ")
    ("snow-wind"                . " ")
    ("snowflake-cold"           . " ")
    ("sprinkle"                 . " ")
    ("square-rss"               . " ")
    ("star"                     . " ")
    ("stars"                    . " ")
    ("sticky_note"              . " ")
    ("style"                    . " ")
    ("stylelint"                . " ")
    ("stylus"                   . " ")
    ("svelte"                   . " ")
    ("swift"                    . " ")
    ("tag"                      . " ")
    ("tcl"                      . " ")
    ("terminal"                 . " ")
    ("terraform"                . " ")
    ("test-directory"           . " ")
    ("test-js"                  . " ")
    ("test-react"               . "󰜈 ")
    ("test-ruby"                . " ")
    ("test-typescript"          . " ")
    ("tex"                      . " ")
    ("thunderstorm"             . " ")
    ("tools"                    . " ")
    ("tornado"                  . " ")
    ("trash"                    . " ")
    ("tsx-alt"                  . "󰛦 ")
    ("typescript-alt"           . "󰛦 ")
    ("vagrant"                  . " ")
    ("verilog"                  . " ")
    ("vertexshader"             . " ")
    ("vhdl"                     . " ")
    ("vue"                      . "﵂ ")
    ("wand-magic-sparkles"      . " ")
    ("webpack"                  . "󰜫 ")
    ("webpack-old"              . "󰜫 ")
    ("workspace"                . " ")
    ("yarn"                     . " ")
    ("zig"                      . " ")
    ("apache"                   . " ")
    ("chevron-up"               . " ")
    ("chevron-down"             . " ")
    ("chevron-left"             . " ")
    ("chevron-right"            . " ")
    ("file-symlink-directory"   . "󰉒 ")
    ("repo"                     . " ")
    ("file-submodule"           . "󰉒 ")
    ("visualstudio"             . "󰘐 ")
    ("collections_bookmark"     . " ")
    ("bookmarks"                . " ")
    ("color"                    . " ")
    ("command"                  . "󰘳 ")
    ("macro"                    . " ")
    ("function"                 . " ")
    ("wrench"                   . " ")
    ("variable"                 . " ")
    ("variable-local"           . " ")
    ("symbol"                   . " ")
    ("error"                    . " ")
    ("ban"                      . " ")
    ("warning"                  . " ")
    ("buffer"                   . "﬘ ")
    ("check"                    . " ")
    ("symbol-array"             . " ")
    ("symbol-boolean"           . " ")
    ("symbol-class"             . " ")
    ("symbol-color"             . " ")
    ("symbol-constant"          . " ")
    ("symbol-enumerator-member" . " ")
    ("symbol-enumerator"        . " ")
    ("symbol-event"             . " ")
    ("symbol-field"             . " ")
    ("symbol-file"              . " ")
    ("symbol-interface"         . " ")
    ("symbol-key"               . " ")
    ("symbol-keyword"           . " ")
    ("symbol-method"            . " ")
    ("symbol-misc"              . " ")
    ("symbol-namespace"         . " ")
    ("symbol-numeric"           . " ")
    ("symbol-operator"          . " ")
    ("symbol-parameter"         . " ")
    ("symbol-property"          . " ")
    ("symbol-ruler"             . " ")
    ("symbol-snippet"           . " ")
    ("symbol-string"            . " ")
    ("symbol-structure"         . " ")
    ("symbol-variable"          . " ")
    ("references"               . " ")
    ))

(provide 'icon-tools-data-nerd)

;; icon-tools-data-nerd.el ends here
